name: money_monitoring
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.3.8
  firebase_core: 1.7.0
  firebase_auth: 3.1.3
  google_sign_in: 5.1.0
  cloud_firestore: 2.5.3
  intl: 0.17.0
  dropdown_search: 1.0.3
  image_picker: 0.8.4+1
  firebase_storage: 10.0.5
  random_string: 2.3.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/logo/
  uses-material-design: true

